SKILLS_DB = [
    "python",
    "machine learning",
    "nlp",
    "tensorflow",
    "pytorch",
    "opencv",
    "streamlit",
    "sql",
    "data analysis",
    "pandas",
    "numpy",
    "scikit learn",
    "generative ai",
    "langchain",
    "rag",
    "computer vision",
    "flask",
    "fastapi",
    "git",
    "github",
    "deep learning",
    "image processing",
    "model deployment",
    "data visualization",
    "power bi",
    "excel",
    "statistics",
    "llm",
    "ai agents",
    "prompt engineering",
    "statistics",
"data visualization",
"power bi",
"tableau",
"excel",
"business analysis",
"communication",
"problem solving",
"documentation",
"technical writing",
"content writing",
"product management",
"user research",
"analytics",
"market research",
"project management",
"team collaboration",
"time management",
"reporting",
"seo",
"hr analytics",
"ats",
"customer support",
"operations",
"process improvement",
"presentation",
"client communication",
"data labeling",
"content review",
"quality analysis",
"automation",
"no code tools",
"workflow design",
"product thinking",
"research",
"markdown",
"docker",
"kubernetes",
"cloud",
"aws",
"azure",
"gcp",
"linux",
"networking",
"security",
"log analysis",
"risk assessment",
"incident response",
"etl",
"data pipelines",
"spark",
"airflow",
"databases",
"data warehousing",
"api development",
"oop",
"data structures",
"algorithms",
"react",
"mlops",
"ci cd",
"monitoring",
"model evaluation",
"dashboarding",
"transformers",
"text preprocessing",
"image processing",
"model deployment",
"fastapi",
"flask",
"langchain"
]

def extract_skills(text):
    detected_skills = []

    text = text.lower()

    for skill in SKILLS_DB:
        if skill.lower() in text:
            detected_skills.append(skill)

    return list(set(detected_skills))